config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'articles#index'
  
  resources :users
  get 'signup' => 'users#new'
	
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if
    session[:user_id]
  end
  
  def require_user
    redirect_to '/login' unless current_user
  end
  
  def logged_in
    redirect_to '/' if current_user
  end  
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user, except: [:index]
  def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :author, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in
  def new
  end
  
  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to 'login'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in, except: [:show, :update]
  def new
    @user = User.new
  end
  
  def create 
  @user = User.new(user_params) 
  	if @user.save 
    	session[:user_id] = @user.id 
    	redirect_to '/' 
  	else 
    	redirect_to '/signup' 
  	end 
	end
  
  def show
    @user = User.find_by(params[:id])
  end
  
  def update
    @user = User.find_by(params[:id])
    @user.update_attributes(user_params)
    if @user.save
      flash[:success] = "Succesfully updated!"
    	redirect_to user_path
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="update-article">
  <div class="container">

    <%= form_for(@article) do |f| %>    
      <%= f.text_field :title %>
      <%= f.text_field :author %>
      <%= f.text_area :body %>

      <%= f.submit "Save", :class => "btn-submit" %>
    <% end %>

  </div>
</div>

app/views/articles/index.html.erb
<div class="articles">
  <div class="container">
    
    <% @articles.each do |article| %>
    <div class="article">
      <p class="date"><%= article.created_at.strftime('%b %d') %></p>
      <!-- http://stackoverflow.com/questions/1086360/how-do-i-wrap-link-to-around-some-html-ruby-code -->
      <%= link_to(article) do %>
        <h2><%= article.title %></h2>
      <% end %>
      <p class="author">by <%= article.author %></p>
      <p class="article_content"><%= truncate(article.body , :length => 140) %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="new-article">
  <div class="container">

    <%= form_for(@article) do |f| %>    
      <%= f.text_field :title %>
      <%= f.text_field :author %>
      <%= f.text_area :body %>

      <%= f.submit "Save" %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="article">
  <div class="container">
    <p class="date"><%= @article.created_at.strftime('%b %d') %></p>
    <h2><%= @article.title %></h2>
    <p class="author">by <%= @article.author %></p>
    <p class="article_content"><%= @article.body %></p>

    <!-- Your code here -->

    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newstand</title>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:300,700,100,400' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="header">
      <div class="container">
        <%= link_to(root_path) do %>
          <h1><span class="dark">n</span>ewstand</h1>
        <% end %>

        <div class="nav pull-right">
          
          <% if current_user %> 
            <ul> 
              <li><%= current_user.email %></li>
              <li><%= link_to "settings", user_path(current_user.id) %></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li> 
            </ul> 
          <% else %> 
            <ul> 
              <li><%= link_to "Login", 'login' %></li> 
              <li><%= link_to "Signup", 'signup' %></li> 
            </ul> 
          <% end %>

        </div>
      </div>
    </div>


    <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<div class="signup">
  <div class="container">
    
    <!-- Your form here -->
    <div class="form">

    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>

  
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="login">
  <div class="container">
   
    <%= form_for(@user) do |f| %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    
      <%= f.label :email %>
      <%= f.email_field :email %>
    
      <%= f.submit "Update my account" %>
    <% end %>
		
    <% if flash[:success] %>
    	<div class="success"><%= flash[:success] %></div>
  	<% end %>
  </div>
</div>